// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace efpicturegallery.migrations.Migrations
{
    [DbContext(typeof(Model.DbContext))]
    [Migration("20200713100126_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Model+Gallery", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("TEXT");

                    b.HasKey("Name")
                        .HasName("pk_galleries");

                    b.ToTable("galleries");
                });

            modelBuilder.Entity("Model+GalleryTag", b =>
                {
                    b.Property<string>("Gallery")
                        .HasColumnName("gallery")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnName("tag")
                        .HasColumnType("TEXT");

                    b.HasKey("Gallery", "Tag")
                        .HasName("pk_gallery_tags");

                    b.HasIndex("Tag")
                        .HasName("ix_gallery_tags_tag");

                    b.ToTable("gallery_tags");
                });

            modelBuilder.Entity("Model+Picture", b =>
                {
                    b.Property<string>("Filename")
                        .HasColumnName("filename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gallery")
                        .HasColumnName("gallery")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnName("created")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnName("height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnName("width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Filename", "Gallery")
                        .HasName("pk_pictures");

                    b.HasIndex("Gallery")
                        .HasName("ix_pictures_gallery");

                    b.ToTable("pictures");
                });

            modelBuilder.Entity("Model+Tag", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name")
                        .HasName("pk_tags");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Model+GalleryTag", b =>
                {
                    b.HasOne("Model+Gallery", "GalleryNav")
                        .WithMany("TagsSet")
                        .HasForeignKey("Gallery")
                        .HasConstraintName("fk_tags_gallery")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model+Tag", "TagNav")
                        .WithMany("GalleriesSet")
                        .HasForeignKey("Tag")
                        .HasConstraintName("fk_tags_tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model+Picture", b =>
                {
                    b.HasOne("Model+Gallery", "GalleryNav")
                        .WithMany("PicturesSet")
                        .HasForeignKey("Gallery")
                        .HasConstraintName("fk_gallery_pictures");
                });
#pragma warning restore 612, 618
        }
    }
}
